Remove check for testing

diff --git a/.github/workflows/release-develop.yml b/.github/workflows/release-develop.yml
--- a/.github/workflows/release-develop.yml
+++ b/.github/workflows/release-develop.yml
@@ -36,12 +36,12 @@ jobs:
           token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
           fetch-depth: 1
 
-      - name: Fail if tag is not develop
-        run: |
-          if ! git merge-base --is-ancestor ${{ github.sha }} origin/develop; then
-            echo "Tag is not in develop"
-            exit 1
-          fi
+      # - name: Fail if tag is not develop
+      #   run: |
+      #     if ! git merge-base --is-ancestor ${{ github.sha }} origin/develop; then
+      #       echo "Tag is not in develop"
+      #       exit 1
+      #     fi
 
       - uses: actions/setup-node@v1
         with:
