Remove check

diff --git a/.github/workflows/tag-prerelease.yml b/.github/workflows/tag-prerelease.yml
--- a/.github/workflows/tag-prerelease.yml
+++ b/.github/workflows/tag-prerelease.yml
@@ -23,11 +23,11 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Fail if branch is not develop
-        if: github.ref != 'refs/heads/develop'
-        run: |
-          echo "Ref is not develop, you must run this job from develop."
-          exit 1
+      # - name: Fail if branch is not develop
+      #   if: github.ref != 'refs/heads/develop'
+      #   run: |
+      #     echo "Ref is not develop, you must run this job from develop."
+      #     exit 1
       - uses: actions/checkout@v2
         with:
           submodules: true
